image: ruby:3.0

cache:
  paths:
  - vendor

test:
  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - bundle exec middleman build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - mkdir public
  - bundle exec middleman build --build-dir=public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
